swagger: "2.0"
info:
  description: "Just a simple API to manage users"
  version: "1.0.0"
  title: "User management API"
host: "petstore.swagger.io"
basePath: "/v2"
paths:
  /user:
    post:
      operationId: createUser
      x-jvm-package: examples.user
      parameters:
      - in: body
        name: user
        schema:
          $ref: '#/definitions/User'
      responses:
        201:
          description: Successful
        403:
          description: Unsuccessful
  /user/{id}:
    get:
      operationId: getUser
      x-jvm-package: examples.user
      produces:
      - application/json
      parameters:
      - in: path
        required: true
        name: id
        type: integer
        format: int64
      responses:
        200:
          description: Successful
          schema:
            $ref: '#/definitions/User'
        404:
          description: Unsuccessful
          schema:
            type: string
  /user/{id}/friends:
    get:
      operationId: getUserFriends
      x-jvm-package: examples.friends
      parameters:
      - in: path
        required: true
        name: id
        type: integer
        format: int64
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: integer
              format: int64
        404:
          description: Unsuccessful
definitions:
  User:
    type: object
    required:
      - full_name
    properties:
      id:
        type: integer
        format: int64
      full_name:
        type: string
      nickname:
        type: string
      date_joined:
        type: string
        format: date-time
      date_modified:
        type: string
        format: date-time
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType
  Cat:
    description: A representation of a cat
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        huntingSkill:
          type: string
          description: The measured skill for hunting
          default: lazy
          enum:
          - clueless
          - lazy
          - adventurous
          - aggressive
      required:
      - huntingSkill
  Dog:
    description: A representation of a dog
    allOf:
    - $ref: '#/definitions/Pet'
    - type: object
      properties:
        packSize:
          type: integer
          format: int32
          description: the size of the pack the dog is from
          default: 0
          minimum: 0
      required:
      - packSize
